#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
CREATE USER asm3 WITH PASSWORD 'asm3';
CREATE DATABASE asm;
GRANT ALL PRIVILEGES ON DATABASE asm TO asm3;
EOSQL
