# More indexes we should have
add_index(dbo, "animal_AgeGroup", "animal", "AgeGroup")
add_index(dbo, "animal_BreedName", "animal", "BreedName")
add_index(dbo, "animal_RabiesTag", "animal", "RabiesTag")
add_index(dbo, "animal_TattooNumber", "animal", "TattooNumber")
add_index(dbo, "owner_MembershipNumber", "owner", "MembershipNumber")
add_index(dbo, "animallost_AreaLost", "animallost", "AreaLost")
add_index(dbo, "animallost_AreaPostcode", "animallost", "AreaPostcode")
add_index(dbo, "animalfound_AreaFound", "animalfound", "AreaFound")
add_index(dbo, "animalfound_AreaPostcode", "animalfound", "AreaPostcode")
add_index(dbo, "animalwaitinglist_AnimalDescription", "animalwaitinglist", "AnimalDescription", partial = True)
add_index(dbo, "animalwaitinglist_OwnerID", "animalwaitinglist", "OwnerID")
add_index(dbo, "animalfound_AnimalTypeID", "animalfound", "AnimalTypeID")
add_index(dbo, "animallost_AnimalTypeID", "animallost", "AnimalTypeID")
add_index(dbo, "media_LinkTypeID", "media", "LinkTypeID")
add_index(dbo, "media_WebsitePhoto", "media", "WebsitePhoto")
add_index(dbo, "media_WebsiteVideo", "media", "WebsiteVideo")
add_index(dbo, "media_DocPhoto", "media", "DocPhoto")
add_index(dbo, "adoption_MovementType", "adoption", "MovementType")
add_index(dbo, "adoption_ReservationDate", "adoption", "ReservationDate")
add_index(dbo, "adoption_ReservationCancelledDate", "adoption", "ReservationCancelledDate")