# add second contact fields to owner table
add_column(dbo, "owner", "OwnerTitle2", dbo.type_shorttext)
add_column(dbo, "owner", "OwnerInitials2", dbo.type_shorttext)
add_column(dbo, "owner", "OwnerForeNames2", dbo.type_shorttext)
add_column(dbo, "owner", "OwnerSurname2", dbo.type_shorttext)
add_column(dbo, "owner", "WorkTelephone2", dbo.type_shorttext)
add_column(dbo, "owner", "MobileTelephone2", dbo.type_shorttext)
add_column(dbo, "owner", "EmailAddress2", dbo.type_shorttext)
add_index(dbo, "owner_OwnerTitle2", "owner", "OwnerTitle2")
add_index(dbo, "owner_OwnerInitials2", "owner", "OwnerInitials2")
add_index(dbo, "owner_OwnerForeNames2", "owner", "OwnerForeNames2")
add_index(dbo, "owner_OwnerSurname2", "owner", "OwnerSurname2")
add_index(dbo, "owner_WorkTelephone2", "owner", "WorkTelephone2")
add_index(dbo, "owner_MobileTelephone2", "owner", "MobileTelephone2")
add_index(dbo, "owner_EmailAddress2", "owner", "EmailAddress2")
execute(dbo,"UPDATE owner SET OwnerTitle2='', OwnerInitials2='', OwnerForeNames2='', OwnerSurname2='', WorkTelephone2='', MobileTelephone2='', EmailAddress2=''")